import pandas as pd

from rest_framework.decorators import api_view, parser_classes
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.utils import timezone

from reportlab.pdfgen import canvas

from .models import Dataset, UploadHistory
from .serializers import UploadHistorySerializer


# ================= UPLOAD CSV =================
@csrf_exempt
@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def upload_csv(request):
    file = request.FILES.get('file')
    if not file:
        return Response({"error": "No file uploaded"}, status=400)

    df = pd.read_csv(file)

    # 🔑 FIX: strip spaces from column names
    df.columns = df.columns.str.strip()

    required_cols = ["Flowrate", "Pressure", "Temperature", "Type"]
    for col in required_cols:
        if col not in df.columns:
            return Response(
                {"error": f"Missing column: {col}"},
                status=400
            )

    total = int(len(df))
    avg_flowrate = float(df["Flowrate"].mean())
    avg_pressure = float(df["Pressure"].mean())
    avg_temperature = float(df["Temperature"].mean())
    type_distribution = df["Type"].value_counts().to_dict()

    summary = {
        "total_count": total,
        "avg_flowrate": avg_flowrate,
        "avg_pressure": avg_pressure,
        "avg_temperature": avg_temperature,
        "type_distribution": type_distribution
    }

    Dataset.objects.create(filename=file.name, summary=summary)

    UploadHistory.objects.create(
        filename=file.name,
        total_count=total,
        avg_flowrate=avg_flowrate,
        avg_pressure=avg_pressure,
        avg_temperature=avg_temperature
    )

    old_records = UploadHistory.objects.order_by('-uploaded_at')[5:]
    UploadHistory.objects.filter(id__in=old_records.values('id')).delete()


    return Response(summary, status=200)



# ================= HISTORY API =================
@api_view(['GET'])
def upload_history(request):
    history = UploadHistory.objects.order_by('-uploaded_at')[:5]
    serializer = UploadHistorySerializer(history, many=True)
    return Response(serializer.data)


# ================= PDF REPORT API =================
@api_view(['GET'])
def generate_pdf(request):
    """
    Generate PDF report for the latest uploaded dataset
    """

    latest = UploadHistory.objects.order_by('-uploaded_at').first()

    if not latest:
        return Response({"error": "No data available"}, status=400)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="equipment_report.pdf"'

    p = canvas.Canvas(response)
    width, height = 600, 800

    p.setFont("Helvetica-Bold", 18)
    p.drawString(50, height - 50, "Chemical Equipment Analysis Report")

    p.setFont("Helvetica", 11)
    p.drawString(
        50,
        height - 90,
        f"Generated on: {timezone.now().strftime('%d %b %Y, %I:%M %p')}"
    )
    p.drawString(50, height - 120, f"Source File: {latest.filename}")

    p.line(50, height - 140, 550, height - 140)

    p.setFont("Helvetica-Bold", 13)
    p.drawString(50, height - 170, "Summary Statistics")

    p.setFont("Helvetica", 12)
    p.drawString(70, height - 210, f"Total Equipment: {latest.total_count}")
    p.drawString(70, height - 240, f"Average Flowrate: {round(latest.avg_flowrate, 2)}")
    p.drawString(70, height - 270, f"Average Pressure: {round(latest.avg_pressure, 2)}")
    p.drawString(70, height - 300, f"Average Temperature: {round(latest.avg_temperature, 2)}")

    p.line(50, height - 330, 550, height - 330)

    p.setFont("Helvetica-Oblique", 10)
    p.drawString(
        50,
        50,
        "Generated by Chemical Equipment Parameter Visualizer"
    )

    p.showPage()
    p.save()

    return response
